services:
    node:
        build:
            args:
                DIRECTORY: /usr/src/app
                PRODUCTION: 'false'
            context: .
        environment:
            - DASH_CONTRACT_ID
            - DASH_IDENTITY
            - DASH_MNEMONIC
            - DASH_NAME
        ports:
            - 80:8080
        volumes:
            - ./public:/usr/src/app/public
            - ./resources:/usr/src/app/resources
            - ./routes:/usr/src/app/routes
            - ./store:/usr/src/app/store
            - ./server.js:/usr/src/app/server.js

version: '3.8'
